/* -*- c++ -*- */
/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Tight FPLL fork - tunable loop alpha/beta + AFC time constant. */
/* Tier-3 instrumented (2026-05-02): periodic stderr telemetry. */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "atsc_fpll_tight_impl.h"
#include <gnuradio/io_signature.h>
#include <gnuradio/math.h>
#include <gnuradio/sincos.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <chrono>

namespace gr {
namespace atscplus {

atsc_fpll_tight::sptr atsc_fpll_tight::make(float rate, float alpha, float afc_tau_us)
{
    return gnuradio::make_block_sptr<atsc_fpll_tight_impl>(rate, alpha, afc_tau_us);
}

atsc_fpll_tight_impl::atsc_fpll_tight_impl(float rate, float alpha, float afc_tau_us)
    : sync_block("atscplus_atsc_fpll_tight",
                 io_signature::make(1, 1, sizeof(gr_complex)),
                 // out0 = real VSB (required, unchanged). out1 = OPTIONAL float
                 // IMAGINARY companion for the widely-linear equalizer (2026-07-26,
                 // v2): the vestigial-sideband component the real path discards.
                 // Carrying imag-only (not full complex) halves the WL data flow —
                 // out0 already IS the real part. Existing chains connect only out0
                 // and are byte-for-byte unaffected.
                 io_signature::make2(1, 2, sizeof(float), sizeof(float)))
{
    d_alpha = alpha;
    d_beta = alpha * alpha / 4.0f;
    d_rate = rate;
    d_afc.set_taps(1.0 - exp(-1.0 / rate / (afc_tau_us * 1e-6)));
    d_nco.set_freq((-3e6 + 0.309e6) / rate * 2 * GR_M_PI);
    d_nco.set_phase(0.0);
    d_t0 = std::chrono::steady_clock::now();
    d_total_samples = 0;
    d_window_sum_abs_x = 0.0;
    d_window_sum_x2 = 0.0;
    d_window_max_abs_x = 0.0f;
    d_window_count = 0;
    d_window_in_pwr = 0.0;
    d_window_out_pwr = 0.0;

    // STVT_FPLL_FOLD=1: absorb the downstream dc_blocker_ff + agc_ff here
    // (see header). Parameter envs mirror the python chain's defaults
    // (STVT_DCR_TAPS=32, STVT_AGC_ALPHA=1e-6, STVT_AGC_REFERENCE=4.0) so the
    // folded path computes exactly what the separate blocks would.
    if (const char* p = std::getenv("STVT_FPLL_FOLD")) {
        d_fold = (std::atoi(p) == 1);
    }
    if (d_fold) {
        int D = 32;
        if (const char* p = std::getenv("STVT_DCR_TAPS")) {
            int v = std::atoi(p);
            if (v > 1) D = v;
        }
        if (const char* p = std::getenv("STVT_AGC_ALPHA")) {
            char* e = nullptr; float v = std::strtof(p, &e);
            if (e != p) d_agc_rate = v;
        }
        if (const char* p = std::getenv("STVT_AGC_REFERENCE")) {
            char* e = nullptr; float v = std::strtof(p, &e);
            if (e != p) d_agc_reference = v;
        }
        d_fma0 = std::make_unique<fold_moving_averager_f>(D);
        d_fma1 = std::make_unique<fold_moving_averager_f>(D);
        d_fma2 = std::make_unique<fold_moving_averager_f>(D);
        d_fma3 = std::make_unique<fold_moving_averager_f>(D);
        d_fold_delay = std::make_unique<fold_ring_f>(D - 1);
        std::fprintf(stderr,
                     "[fpll_tight] FOLD active: dc_blocker(D=%d) + agc(rate=%g ref=%g) in-loop\n",
                     D, d_agc_rate, d_agc_reference);
    }

    std::fprintf(stderr,
                 "[fpll_tight] rate=%.0f alpha=%.5f beta=%.3e afc_tau_us=%.1f\n",
                 rate, d_alpha, d_beta, afc_tau_us);
}

atsc_fpll_tight_impl::~atsc_fpll_tight_impl() {}

int atsc_fpll_tight_impl::work(int noutput_items,
                               gr_vector_const_void_star& input_items,
                               gr_vector_void_star& output_items)
{
    auto in = static_cast<const gr_complex*>(input_items[0]);
    auto out = static_cast<float*>(output_items[0]);

    float a_cos, a_sin;
    float x;
    gr_complex result, filtered;

    // --- phase-detector gates (hoisted so both the per-sample and the
    //     block-NCO paths read the same env once). ---
    static const int SAT_MODE = []() -> int {
        if (const char* p = std::getenv("STVT_FPLL_SAT_MODE")) {
            if (std::strcmp(p, "clip") == 0) return 1;
        }
        return 0;
    }();
    static const float MAG_MIN_RMS = []() -> float {
        if (const char* p = std::getenv("STVT_FPLL_MAG_MIN")) {
            char* e = nullptr; float v = std::strtof(p, &e);
            if (e != p) return v;
        }
        return 4.0f;
    }();
    static const float XGATE = []() -> float {
        if (const char* p = std::getenv("STVT_FPLL_XGATE")) {
            char* e = nullptr; float v = std::strtof(p, &e);
            if (e != p && v > 0.0f && v <= (float)M_PI_2) return v;
        }
        return (float)M_PI_2 - 1e-4f;
    }();
    const float mag2_min = MAG_MIN_RMS * MAG_MIN_RMS;

    // STVT_FPLL_BLOCK_NCO=1: freeze the carrier frequency over short blocks of
    // BLK samples. Within a block the NCO mixer is generated by a complex
    // rotation recurrence (one sincosf to seed the phasor + one for the
    // per-sample rotation factor, then B cheap complex multiplies) instead of
    // a sincosf per sample, and the phase-detector + loop filter run ONCE per
    // block (one fast_atan2f instead of B). The corrections are scaled by B so
    // the average loop gain — hence the loop bandwidth and acquisition speed —
    // is preserved (the ATSC pilot loop bandwidth is ~kHz; a per-block update
    // rate of fs/B ≈ 1 MHz is thousands of times faster, so block-rate updating
    // loses no tracking). NOT bit-exact vs the per-sample path (recurrence vs
    // sincosf, block-rate vs sample-rate feedback) — gated on a tei%/top_pid
    // quality A/B, default off.
    static const int BLK = []() -> int {
        if (const char* p = std::getenv("STVT_FPLL_BLOCK_NCO")) {
            if (std::atoi(p) == 1) {
                int b = 16;
                if (const char* q = std::getenv("STVT_FPLL_BLOCK_LEN")) {
                    int v = std::atoi(q);
                    if (v >= 2 && v <= 256) b = v;
                }
                return b;
            }
        }
        return 0;
    }();

    if (BLK > 0) {
        static bool announced = false;
        if (!announced) {
            std::fprintf(stderr, "[fpll_tight] BLOCK_NCO active: blk=%d\n", BLK);
            announced = true;
        }
        int k = 0;
        while (k < noutput_items) {
            int B = noutput_items - k;
            if (B > BLK) B = BLK;

            // Seed the rotation recurrence from the exact NCO phase/frequency.
            // Mixer convention matches the per-sample path: in[k] is multiplied
            // by (sin(phase) + j*cos(phase)). With c = e^{j*phase} that factor
            // is (c.imag, c.real); the per-sample step is c *= w, w = e^{j*inc},
            // applied BEFORE first use to mirror the original step()-then-mix.
            double ph  = d_nco.get_phase();
            double inc = d_nco.get_freq();
            float ws, wc; gr::sincosf((float)inc, &ws, &wc);
            const gr_complex w(wc, ws);
            float cs, cc;  gr::sincosf((float)ph, &cs, &cc);
            gr_complex c(cc, cs);

            gr_complex last_filtered(0.0f, 0.0f);
            for (int j = 0; j < B; j++) {
                c *= w;
                const gr_complex m(c.imag(), c.real());
                gr::fast_cc_multiply(result, in[k], m);
                out[k] = result.real();

                if (d_fold) {
                    float y1 = d_fma0->filter(out[k]);
                    float y2 = d_fma1->filter(y1);
                    float y3 = d_fma2->filter(y2);
                    float y4 = d_fma3->filter(y3);
                    float dly = d_fold_delay->rotate(d_fma0->delayed_sig());
                    float dcb = dly - y4;
                    float o = dcb * d_agc_gain;
                    d_agc_gain += (d_agc_reference - fabsf(o)) * d_agc_rate;
                    if (d_agc_max_gain > 0.0 && d_agc_gain > d_agc_max_gain)
                        d_agc_gain = d_agc_max_gain;
                    out[k] = o;
                }

                last_filtered = d_afc.filter(result);

                d_window_in_pwr += (double)in[k].real() * in[k].real()
                                + (double)in[k].imag() * in[k].imag();
                d_window_out_pwr += (double)out[k] * out[k];
                k++;
            }

            // Advance the frozen NCO phase by the whole block, then wrap.
            double newph = ph + inc * (double)B;
            while (newph > GR_M_PI)  newph -= 2 * GR_M_PI;
            while (newph < -GR_M_PI) newph += 2 * GR_M_PI;
            d_nco.set_phase(newph);

            // One phase-detector evaluation per block on the block's last
            // (most-recently AFC-smoothed) sample; same degenerate-sample gate
            // as the per-sample path. Correction scaled by B to hold loop gain.
            x = gr::fast_atan2f(last_filtered.imag(), last_filtered.real());
            float mag2 = last_filtered.real() * last_filtered.real()
                       + last_filtered.imag() * last_filtered.imag();
            bool degenerate = (mag2 < mag2_min) || (x >= XGATE) || (x <= -XGATE);
            if (degenerate) {
                if (SAT_MODE == 1) {
                    if (x > M_PI_2) x = M_PI_2;
                    else if (x < -M_PI_2) x = -M_PI_2;
                } else {
                    x = 0.0f;
                }
            }
            d_nco.adjust_phase((double)d_alpha * x * (double)B);
            d_nco.adjust_freq((double)d_beta * x * (double)B);

            // Telemetry: treat the block error as applying to all B samples so
            // mean|x|/rms_x stay comparable to the per-sample path.
            float ax = std::fabs(x);
            d_window_sum_abs_x += (double)ax * B;
            d_window_sum_x2 += (double)x * (double)x * B;
            if (ax > d_window_max_abs_x) d_window_max_abs_x = ax;
            d_window_count += B;
        }

        d_total_samples += noutput_items;
        goto telemetry;
    }

    for (int k = 0; k < noutput_items; k++) {
        d_nco.step();
        d_nco.sincos(&a_sin, &a_cos);

        gr::fast_cc_multiply(result, in[k], gr_complex(a_sin, a_cos));

        out[k] = result.real();

        if (d_fold) {
            // Exact replica of dc_blocker_ff_impl::work() long-form branch
            // followed by kernel::agc_ff::scale() — see header note.
            float y1 = d_fma0->filter(out[k]);
            float y2 = d_fma1->filter(y1);
            float y3 = d_fma2->filter(y2);
            float y4 = d_fma3->filter(y3);
            float dly = d_fold_delay->rotate(d_fma0->delayed_sig());
            float dcb = dly - y4;
            float o = dcb * d_agc_gain;
            d_agc_gain += (d_agc_reference - fabsf(o)) * d_agc_rate;
            if (d_agc_max_gain > 0.0 && d_agc_gain > d_agc_max_gain)
                d_agc_gain = d_agc_max_gain;
            out[k] = o;
        }

        // OPTIONAL imaginary companion (widely-linear equalizer feed). The real
        // part is out0; here we emit just the carrier-corrected imaginary part,
        // scaled to match (agc gain in fold mode). Only written if connected.
        if (output_items.size() > 1) {
            auto outi = static_cast<float*>(output_items[1]);
            outi[k] = d_fold ? (result.imag() * d_agc_gain) : result.imag();
        }

        filtered = d_afc.filter(result);
        x = gr::fast_atan2f(filtered.imag(), filtered.real());

        // Degenerate-sample freeze (FIX #1 2026-05-23 + 2026-05-30 phase gate);
        // SAT_MODE / MAG_MIN_RMS / XGATE / mag2_min are read once at the top of
        // work() and shared with the BLOCK_NCO path.
        float mag2 = filtered.real() * filtered.real()
                   + filtered.imag() * filtered.imag();
        bool degenerate = (mag2 < mag2_min) || (x >= XGATE) || (x <= -XGATE);
        if (degenerate) {
            if (SAT_MODE == 1) {
                if (x > M_PI_2) x = M_PI_2;
                else if (x < -M_PI_2) x = -M_PI_2;
            } else {
                x = 0.0f;
            }
        }

        d_nco.adjust_phase(d_alpha * x);
        d_nco.adjust_freq(d_beta * x);

        // Tier-3 telemetry accumulation. Track:
        //  * mean and max |x| (phase-detector error magnitude)
        //  * input complex power and post-mix real power (proxies for AGC drift,
        //    even though AGC itself is downstream — change in upstream level
        //    leaks through here)
        float ax = std::fabs(x);
        d_window_sum_abs_x += ax;
        d_window_sum_x2 += (double)x * (double)x;
        if (ax > d_window_max_abs_x) d_window_max_abs_x = ax;
        d_window_in_pwr += (double)in[k].real() * in[k].real()
                        + (double)in[k].imag() * in[k].imag();
        d_window_out_pwr += (double)out[k] * out[k];
        d_window_count++;
    }

    d_total_samples += noutput_items;

telemetry:
    // Print every ~LOG_EVERY samples (~1.5M @ 16.14MS/s -> ~93ms).  Choose a
    // value that yields ~5 prints/sec to keep correlation with t=30-45s easy.
    constexpr uint64_t LOG_EVERY = 1u << 21; // 2,097,152 samples ≈ 130 ms
    if (d_window_count >= LOG_EVERY) {
        auto now = std::chrono::steady_clock::now();
        double t = std::chrono::duration<double>(now - d_t0).count();
        // Convert NCO phase increment (rad/sample) back to Hz offset.
        double freq_rad = d_nco.get_freq();
        double freq_hz  = freq_rad * d_rate / (2.0 * GR_M_PI);
        double mean_abs_x = d_window_sum_abs_x / (double)d_window_count;
        double rms_x      = std::sqrt(d_window_sum_x2 / (double)d_window_count);
        double in_rms     = std::sqrt(d_window_in_pwr  / (double)d_window_count);
        double out_rms    = std::sqrt(d_window_out_pwr / (double)d_window_count);
        std::fprintf(stderr,
                     "[fpll t=%6.2fs] nco_freq_hz=%+.1f mean|x|=%.5f rms_x=%.5f "
                     "max|x|=%.4f in_rms=%.1f out_rms=%.1f\n",
                     t, freq_hz, mean_abs_x, rms_x, d_window_max_abs_x,
                     in_rms, out_rms);
        std::fflush(stderr);
        d_window_sum_abs_x = 0.0;
        d_window_sum_x2 = 0.0;
        d_window_max_abs_x = 0.0f;
        d_window_in_pwr = 0.0;
        d_window_out_pwr = 0.0;
        d_window_count = 0;
    }

    return noutput_items;
}

} /* namespace atscplus */
} /* namespace gr */
